#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'gps-rtk2','console_scripts','gps_read'
__requires__ = 'gps-rtk2'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('gps-rtk2', 'console_scripts', 'gps_read')()
    )
